# GSE98923 CEMiTool workflow
# Complete one-file reproducible workflow for the 54-sample baseline.
# Soft-thresholding power is fixed explicitly at beta = 10.
#
# Outputs:
# - native CEMiTool HTML report
# - native CEMiTool diagnostic HTML report
# - consolidated HTML, Word, and PDF report
# - editable scientific manuscript draft
# - vector figures and 300-dpi PNG report figures
# - supplementary archive, manifest, checksums, logs, and session information

project_dir <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)

dir.create(
  file.path(project_dir, "scripts"),
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  file.path(project_dir, "templates"),
  recursive = TRUE,
  showWarnings = FALSE
)

writeLines(
  c(
    "# Project setup",
    "",
    "project_dir <- normalizePath(getwd(), winslash = \"/\", mustWork = TRUE)",
    "",
    "dirs <- c(",
    "  \"scripts\",",
    "  \"templates\",",
    "  \"data/raw/geo\",",
    "  \"data/raw/images\",",
    "  \"data/metadata\",",
    "  \"data/processed\",",
    "  \"results/objects\",",
    "  \"results/tables\",",
    "  \"results/figures\",",
    "  \"reports/cemitool\",",
    "  \"reports/diagnostics\",",
    "  \"reports/assets/figures\",",
    "  \"reports/supplementary\",",
    "  \"manuscript\",",
    "  \"docs/reference_images\",",
    "  \"logs\"",
    ")",
    "",
    "invisible(lapply(",
    "  file.path(project_dir, dirs),",
    "  dir.create,",
    "  recursive = TRUE,",
    "  showWarnings = FALSE",
    "))",
    "",
    "if (length(list.files(project_dir, pattern = \"\\\\.Rproj$\")) == 0) {",
    "  writeLines(",
    "    c(",
    "      \"Version: 1.0\",",
    "      \"\",",
    "      \"RestoreWorkspace: No\",",
    "      \"SaveWorkspace: No\",",
    "      \"AlwaysSaveHistory: No\",",
    "      \"Encoding: UTF-8\"",
    "    ),",
    "    file.path(project_dir, \"gse98923_cemitool.Rproj\")",
    "  )",
    "}",
    "",
    "if (!requireNamespace(\"BiocManager\", quietly = TRUE)) {",
    "  install.packages(\"BiocManager\")",
    "}",
    "",
    "bioc_packages <- c(\"GEOquery\", \"CEMiTool\")",
    "missing_bioc <- bioc_packages[",
    "  !vapply(bioc_packages, requireNamespace, logical(1), quietly = TRUE)",
    "]",
    "",
    "if (length(missing_bioc) > 0) {",
    "  BiocManager::install(missing_bioc, ask = FALSE, update = FALSE)",
    "}",
    "",
    "cran_packages <- c(",
    "  \"rmarkdown\",",
    "  \"knitr\",",
    "  \"tinytex\",",
    "  \"zip\"",
    ")",
    "",
    "missing_cran <- cran_packages[",
    "  !vapply(cran_packages, requireNamespace, logical(1), quietly = TRUE)",
    "]",
    "",
    "if (length(missing_cran) > 0) {",
    "  install.packages(missing_cran)",
    "}",
    "",
    "suppressPackageStartupMessages({",
    "  library(GEOquery)",
    "  library(CEMiTool)",
    "})",
    "",
    "# Exact 54-sample selection used by this baseline.",
    "metadata_lines <- c(",
    "  \"SampleName\\tClass\\tGSM\\tCultivar\\tYear\\tStage\\tTimePoint\\tReplicate\\tDayAfterVeraison\\tEvidence\\tGEO_URL\",",
    "  \"GSM2627691\\tCS_FruitSet\\tGSM2627691\\tCabernet Sauvignon\\t2012\\tFruitSet\\t0\\t1\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627691\",",
    "  \"GSM2627692\\tCS_FruitSet\\tGSM2627692\\tCabernet Sauvignon\\t2012\\tFruitSet\\t0\\t2\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627692\",",
    "  \"GSM2627693\\tCS_FruitSet\\tGSM2627693\\tCabernet Sauvignon\\t2012\\tFruitSet\\t0\\t3\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627693\",",
    "  \"GSM2627709\\tCS_Veraison\\tGSM2627709\\tCabernet Sauvignon\\t2012\\tVeraison\\t4\\t1\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627709\",",
    "  \"GSM2627711\\tCS_Veraison\\tGSM2627711\\tCabernet Sauvignon\\t2012\\tVeraison\\t4\\t2\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627711\",",
    "  \"GSM2627713\\tCS_Veraison\\tGSM2627713\\tCabernet Sauvignon\\t2012\\tVeraison\\t4\\t3\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627713\",",
    "  \"GSM2627739\\tCS_Harvest\\tGSM2627739\\tCabernet Sauvignon\\t2012\\tHarvest\\t12\\t1\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627739\",",
    "  \"GSM2627740\\tCS_Harvest\\tGSM2627740\\tCabernet Sauvignon\\t2012\\tHarvest\\t12\\t2\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627740\",",
    "  \"GSM2627741\\tCS_Harvest\\tGSM2627741\\tCabernet Sauvignon\\t2012\\tHarvest\\t12\\t3\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627741\",",
    "  \"GSM2627742\\tCS_FruitSet\\tGSM2627742\\tCabernet Sauvignon\\t2013\\tFruitSet\\t0\\t1\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627742\",",
    "  \"GSM2627743\\tCS_FruitSet\\tGSM2627743\\tCabernet Sauvignon\\t2013\\tFruitSet\\t0\\t2\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627743\",",
    "  \"GSM2627744\\tCS_FruitSet\\tGSM2627744\\tCabernet Sauvignon\\t2013\\tFruitSet\\t0\\t3\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627744\",",
    "  \"GSM2627754\\tCS_Veraison\\tGSM2627754\\tCabernet Sauvignon\\t2013\\tVeraison\\t4\\t1\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627754\",",
    "  \"GSM2627755\\tCS_Veraison\\tGSM2627755\\tCabernet Sauvignon\\t2013\\tVeraison\\t4\\t2\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627755\",",
    "  \"GSM2627756\\tCS_Veraison\\tGSM2627756\\tCabernet Sauvignon\\t2013\\tVeraison\\t4\\t3\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627756\",",
    "  \"GSM2627781\\tCS_Harvest\\tGSM2627781\\tCabernet Sauvignon\\t2013\\tHarvest\\t13\\t1\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627781\",",
    "  \"GSM2627782\\tCS_Harvest\\tGSM2627782\\tCabernet Sauvignon\\t2013\\tHarvest\\t13\\t2\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627782\",",
    "  \"GSM2627783\\tCS_Harvest\\tGSM2627783\\tCabernet Sauvignon\\t2013\\tHarvest\\t13\\t3\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627783\",",
    "  \"GSM2627784\\tCS_FruitSet\\tGSM2627784\\tCabernet Sauvignon\\t2014\\tFruitSet\\t0\\t1\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627784\",",
    "  \"GSM2627785\\tCS_FruitSet\\tGSM2627785\\tCabernet Sauvignon\\t2014\\tFruitSet\\t0\\t2\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627785\",",
    "  \"GSM2627786\\tCS_FruitSet\\tGSM2627786\\tCabernet Sauvignon\\t2014\\tFruitSet\\t0\\t3\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627786\",",
    "  \"GSM2627793\\tCS_Veraison\\tGSM2627793\\tCabernet Sauvignon\\t2014\\tVeraison\\t3\\t1\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627793\",",
    "  \"GSM2627794\\tCS_Veraison\\tGSM2627794\\tCabernet Sauvignon\\t2014\\tVeraison\\t3\\t2\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627794\",",
    "  \"GSM2627795\\tCS_Veraison\\tGSM2627795\\tCabernet Sauvignon\\t2014\\tVeraison\\t3\\t3\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627795\",",
    "  \"GSM2627820\\tCS_Harvest\\tGSM2627820\\tCabernet Sauvignon\\t2014\\tHarvest\\t12\\t1\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627820\",",
    "  \"GSM2627821\\tCS_Harvest\\tGSM2627821\\tCabernet Sauvignon\\t2014\\tHarvest\\t12\\t2\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627821\",",
    "  \"GSM2627822\\tCS_Harvest\\tGSM2627822\\tCabernet Sauvignon\\t2014\\tHarvest\\t12\\t3\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627822\",",
    "  \"GSM2627823\\tPN_FruitSet\\tGSM2627823\\tPinot noir\\t2012\\tFruitSet\\t0\\t1\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627823\",",
    "  \"GSM2627824\\tPN_FruitSet\\tGSM2627824\\tPinot noir\\t2012\\tFruitSet\\t0\\t2\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627824\",",
    "  \"GSM2627825\\tPN_FruitSet\\tGSM2627825\\tPinot noir\\t2012\\tFruitSet\\t0\\t3\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627825\",",
    "  \"GSM2627835\\tPN_Veraison\\tGSM2627835\\tPinot noir\\t2012\\tVeraison\\t4\\t1\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627835\",",
    "  \"GSM2627836\\tPN_Veraison\\tGSM2627836\\tPinot noir\\t2012\\tVeraison\\t4\\t2\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627836\",",
    "  \"GSM2627837\\tPN_Veraison\\tGSM2627837\\tPinot noir\\t2012\\tVeraison\\t4\\t3\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627837\",",
    "  \"GSM2627850\\tPN_Harvest\\tGSM2627850\\tPinot noir\\t2012\\tHarvest\\t9\\t1\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627850\",",
    "  \"GSM2627851\\tPN_Harvest\\tGSM2627851\\tPinot noir\\t2012\\tHarvest\\t9\\t2\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627851\",",
    "  \"GSM2627852\\tPN_Harvest\\tGSM2627852\\tPinot noir\\t2012\\tHarvest\\t9\\t3\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627852\",",
    "  \"GSM2627853\\tPN_FruitSet\\tGSM2627853\\tPinot noir\\t2013\\tFruitSet\\t0\\t1\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627853\",",
    "  \"GSM2627854\\tPN_FruitSet\\tGSM2627854\\tPinot noir\\t2013\\tFruitSet\\t0\\t2\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627854\",",
    "  \"GSM2627855\\tPN_FruitSet\\tGSM2627855\\tPinot noir\\t2013\\tFruitSet\\t0\\t3\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627855\",",
    "  \"GSM2627862\\tPN_Veraison\\tGSM2627862\\tPinot noir\\t2013\\tVeraison\\t3\\t1\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627862\",",
    "  \"GSM2627863\\tPN_Veraison\\tGSM2627863\\tPinot noir\\t2013\\tVeraison\\t3\\t2\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627863\",",
    "  \"GSM2627864\\tPN_Veraison\\tGSM2627864\\tPinot noir\\t2013\\tVeraison\\t3\\t3\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627864\",",
    "  \"GSM2627883\\tPN_Harvest\\tGSM2627883\\tPinot noir\\t2013\\tHarvest\\t10\\t1\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627883\",",
    "  \"GSM2627884\\tPN_Harvest\\tGSM2627884\\tPinot noir\\t2013\\tHarvest\\t10\\t2\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627884\",",
    "  \"GSM2627885\\tPN_Harvest\\tGSM2627885\\tPinot noir\\t2013\\tHarvest\\t10\\t3\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627885\",",
    "  \"GSM2627886\\tPN_FruitSet\\tGSM2627886\\tPinot noir\\t2014\\tFruitSet\\t0\\t1\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627886\",",
    "  \"GSM2627887\\tPN_FruitSet\\tGSM2627887\\tPinot noir\\t2014\\tFruitSet\\t0\\t2\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627887\",",
    "  \"GSM2627888\\tPN_FruitSet\\tGSM2627888\\tPinot noir\\t2014\\tFruitSet\\t0\\t3\\t\\tProtocol-derived: sampling begins at fruit set\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627888\",",
    "  \"GSM2627895\\tPN_Veraison\\tGSM2627895\\tPinot noir\\t2014\\tVeraison\\t3\\t1\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627895\",",
    "  \"GSM2627896\\tPN_Veraison\\tGSM2627896\\tPinot noir\\t2014\\tVeraison\\t3\\t2\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627896\",",
    "  \"GSM2627897\\tPN_Veraison\\tGSM2627897\\tPinot noir\\t2014\\tVeraison\\t3\\t3\\t0\\tExplicit GEO: day after veraison = 0\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627897\",",
    "  \"GSM2627919\\tPN_Harvest\\tGSM2627919\\tPinot noir\\t2014\\tHarvest\\t11\\t1\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627919\",",
    "  \"GSM2627920\\tPN_Harvest\\tGSM2627920\\tPinot noir\\t2014\\tHarvest\\t11\\t2\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627920\",",
    "  \"GSM2627921\\tPN_Harvest\\tGSM2627921\\tPinot noir\\t2014\\tHarvest\\t11\\t3\\t\\tProtocol-derived: final time point; sampling until harvest (24.5 Brix)\\thttps://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2627921\"",
    ")",
    "",
    "samples <- read.delim(",
    "  text = paste(metadata_lines, collapse = \"\\n\"),",
    "  sep = \"\\t\",",
    "  header = TRUE,",
    "  stringsAsFactors = FALSE,",
    "  check.names = FALSE,",
    "  colClasses = \"character\",",
    "  na.strings = character(0)",
    ")",
    "",
    "stopifnot(",
    "  nrow(samples) == 54,",
    "  !anyDuplicated(samples$SampleName),",
    "  !anyDuplicated(samples$GSM)",
    ")",
    "",
    "samples_file <- file.path(project_dir, \"data/metadata/samples.tsv\")",
    "",
    "if (file.exists(samples_file)) {",
    "  existing <- read.delim(",
    "    samples_file,",
    "    sep = \"\\t\",",
    "    header = TRUE,",
    "    stringsAsFactors = FALSE,",
    "    check.names = FALSE,",
    "    colClasses = \"character\",",
    "    na.strings = character(0)",
    "  )",
    "",
    "  if (!identical(existing, samples)) {",
    "    stop(",
    "      \"data/metadata/samples.tsv differs from the canonical \",",
    "      \"54-sample selection embedded in the workflow.\"",
    "    )",
    "  }",
    "} else {",
    "  write.table(",
    "    samples,",
    "    samples_file,",
    "    sep = \"\\t\",",
    "    quote = FALSE,",
    "    row.names = FALSE,",
    "    na = \"\"",
    "  )",
    "}",
    "",
    "phenotypes <- samples[, c(\"SampleName\", \"Class\")]",
    "",
    "write.table(",
    "  phenotypes,",
    "  file.path(project_dir, \"data/metadata/phenotypes.tsv\"),",
    "  sep = \"\\t\",",
    "  quote = FALSE,",
    "  row.names = FALSE",
    ")",
    "",
    "image_manifest <- file.path(",
    "  project_dir,",
    "  \"data/metadata/sample_images.tsv\"",
    ")",
    "",
    "if (!file.exists(image_manifest)) {",
    "  write.table(",
    "    data.frame(",
    "      SampleName = samples$SampleName,",
    "      GSM = samples$GSM,",
    "      file = \"\",",
    "      source = \"\",",
    "      date = \"\",",
    "      notes = \"\",",
    "      stringsAsFactors = FALSE",
    "    ),",
    "    image_manifest,",
    "    sep = \"\\t\",",
    "    quote = FALSE,",
    "    row.names = FALSE",
    "  )",
    "}",
    "",
    "writeLines(",
    "  c(",
    "    \"# Experimental design\",",
    "    \"\",",
    "    \"GEO accession: GSE98923\",",
    "    \"\",",
    "    \"- Cultivars: Cabernet Sauvignon and Pinot noir\",",
    "    \"- Developmental stages: FruitSet, Veraison, Harvest\",",
    "    \"- Years: 2012, 2013, 2014\",",
    "    \"- Replicates: 3 per cultivar-stage-year combination\",",
    "    \"- Total samples: 54\",",
    "    \"\",",
    "    \"The canonical sample selection is embedded in the analysis scripts.\"",
    "  ),",
    "  file.path(project_dir, \"docs/experimental_design.md\")",
    ")",
    "",
    "references_file <- file.path(project_dir, \"manuscript/references.bib\")",
    "if (!file.exists(references_file)) {",
    "  writeLines(",
    "    c(",
    "      \"% Add verified bibliographic references here.\",",
    "      \"% Do not add unverified citations automatically.\"",
    "    ),",
    "    references_file",
    "  )",
    "}",
    "",
    "message(\"Project setup complete.\")"
  ),
  file.path(project_dir, "scripts/00_setup.R"),
  useBytes = TRUE
)

writeLines(
  c(
    "# Download public GEO data",
    "",
    "project_dir <- normalizePath(getwd(), winslash = \"/\", mustWork = TRUE)",
    "geo_dir <- file.path(project_dir, \"data/raw/geo\")",
    "dir.create(geo_dir, recursive = TRUE, showWarnings = FALSE)",
    "",
    "rpkm_pattern <- \"GSE98923_RPKM_2012-2013-2014_controls\\\\.txt\\\\.gz$\"",
    "",
    "rpkm_files <- list.files(",
    "  geo_dir,",
    "  pattern = rpkm_pattern,",
    "  full.names = TRUE,",
    "  recursive = TRUE",
    ")",
    "",
    "if (length(rpkm_files) == 0) {",
    "  GEOquery::getGEOSuppFiles(",
    "    \"GSE98923\",",
    "    makeDirectory = TRUE,",
    "    baseDir = geo_dir",
    "  )",
    "",
    "  rpkm_files <- list.files(",
    "    geo_dir,",
    "    pattern = rpkm_pattern,",
    "    full.names = TRUE,",
    "    recursive = TRUE",
    "  )",
    "}",
    "",
    "if (length(rpkm_files) != 1) {",
    "  stop(\"Could not identify a unique GSE98923 RPKM file.\")",
    "}",
    "",
    "gse_rds <- file.path(",
    "  geo_dir,",
    "  \"gse98923_expression_set.rds\"",
    ")",
    "",
    "if (!file.exists(gse_rds)) {",
    "  gse_list <- GEOquery::getGEO(",
    "    \"GSE98923\",",
    "    GSEMatrix = TRUE,",
    "    getGPL = FALSE",
    "  )",
    "",
    "  if (length(gse_list) < 1) {",
    "    stop(\"GEOquery returned no ExpressionSet for GSE98923.\")",
    "  }",
    "",
    "  saveRDS(gse_list[[1]], gse_rds)",
    "}",
    "",
    "message(\"GEO data available.\")"
  ),
  file.path(project_dir, "scripts/01_download_geo.R"),
  useBytes = TRUE
)

writeLines(
  c(
    "# Prepare sample mapping and expression matrices",
    "",
    "project_dir <- normalizePath(getwd(), winslash = \"/\", mustWork = TRUE)",
    "",
    "samples <- read.delim(",
    "  file.path(project_dir, \"data/metadata/samples.tsv\"),",
    "  sep = \"\\t\",",
    "  header = TRUE,",
    "  stringsAsFactors = FALSE,",
    "  check.names = FALSE",
    ")",
    "",
    "gse <- readRDS(",
    "  file.path(project_dir, \"data/raw/geo/gse98923_expression_set.rds\")",
    ")",
    "",
    "geo_pheno <- Biobase::pData(gse)",
    "",
    "geo_gsm <- if (\"geo_accession\" %in% names(geo_pheno)) {",
    "  as.character(geo_pheno$geo_accession)",
    "} else {",
    "  rownames(geo_pheno)",
    "}",
    "",
    "description_cols <- grep(",
    "  \"description\",",
    "  names(geo_pheno),",
    "  ignore.case = TRUE,",
    "  value = TRUE",
    ")",
    "",
    "if (length(description_cols) == 0) {",
    "  stop(\"No GEO description column was found.\")",
    "}",
    "",
    "get_description <- function(i) {",
    "  x <- as.character(geo_pheno[i, description_cols, drop = TRUE])",
    "  x <- x[!is.na(x) & nzchar(x)]",
    "  if (length(x) == 0) NA_character_ else x[[1]]",
    "}",
    "",
    "geo_map <- data.frame(",
    "  GSM = geo_gsm,",
    "  Description = vapply(",
    "    seq_len(nrow(geo_pheno)),",
    "    get_description,",
    "    character(1)",
    "  ),",
    "  stringsAsFactors = FALSE",
    ")",
    "",
    "selected_map <- geo_map[",
    "  match(samples$GSM, geo_map$GSM),",
    "  ,",
    "  drop = FALSE",
    "]",
    "",
    "if (anyNA(selected_map$GSM)) {",
    "  stop(\"At least one selected GSM accession was not found in GEO metadata.\")",
    "}",
    "",
    "write.table(",
    "  cbind(samples, GEO_Description = selected_map$Description),",
    "  file.path(project_dir, \"data/metadata/sample_geo_map.tsv\"),",
    "  sep = \"\\t\",",
    "  quote = FALSE,",
    "  row.names = FALSE",
    ")",
    "",
    "rpkm_files <- list.files(",
    "  file.path(project_dir, \"data/raw/geo\"),",
    "  pattern = \"GSE98923_RPKM_2012-2013-2014_controls\\\\.txt\\\\.gz$\",",
    "  full.names = TRUE,",
    "  recursive = TRUE",
    ")",
    "",
    "if (length(rpkm_files) != 1) {",
    "  stop(\"Could not identify a unique GSE98923 RPKM file.\")",
    "}",
    "",
    "raw <- read.delim(",
    "  gzfile(rpkm_files[[1]]),",
    "  sep = \"\\t\",",
    "  header = TRUE,",
    "  check.names = FALSE,",
    "  stringsAsFactors = FALSE",
    ")",
    "",
    "gene_id <- as.character(raw[[1]])",
    "",
    "if (anyNA(gene_id) || any(!nzchar(gene_id)) || anyDuplicated(gene_id)) {",
    "  stop(\"Invalid or duplicated gene identifiers in the RPKM matrix.\")",
    "}",
    "",
    "expression_names <- names(raw)[-1]",
    "",
    "if (all(samples$GSM %in% expression_names)) {",
    "  source_columns <- samples$GSM",
    "} else if (all(selected_map$Description %in% expression_names)) {",
    "  source_columns <- selected_map$Description",
    "} else if (",
    "  all(make.names(selected_map$Description) %in% make.names(expression_names))",
    ") {",
    "  idx <- match(",
    "    make.names(selected_map$Description),",
    "    make.names(expression_names)",
    "  )",
    "  source_columns <- expression_names[idx]",
    "} else {",
    "  stop(\"Selected samples could not be mapped safely to the RPKM matrix.\")",
    "}",
    "",
    "expression_rpkm <- raw[, source_columns, drop = FALSE]",
    "expression_rpkm[] <- lapply(expression_rpkm, as.numeric)",
    "",
    "rownames(expression_rpkm) <- gene_id",
    "colnames(expression_rpkm) <- samples$SampleName",
    "",
    "if (",
    "  anyNA(as.matrix(expression_rpkm)) ||",
    "  any(!is.finite(as.matrix(expression_rpkm))) ||",
    "  any(as.matrix(expression_rpkm) < 0)",
    ") {",
    "  stop(\"The selected expression matrix contains invalid values.\")",
    "}",
    "",
    "expression_log2rpkm <- log2(expression_rpkm + 1)",
    "",
    "write_expression <- function(x, path) {",
    "  out <- data.frame(",
    "    gene_id = rownames(x),",
    "    x,",
    "    check.names = FALSE",
    "  )",
    "",
    "  write.table(",
    "    out,",
    "    path,",
    "    sep = \"\\t\",",
    "    quote = FALSE,",
    "    row.names = FALSE",
    "  )",
    "}",
    "",
    "write_expression(",
    "  expression_rpkm,",
    "  file.path(project_dir, \"data/processed/expression_rpkm.tsv\")",
    ")",
    "",
    "write_expression(",
    "  expression_log2rpkm,",
    "  file.path(project_dir, \"data/processed/expression_log2rpkm.tsv\")",
    ")",
    "",
    "saveRDS(",
    "  expression_log2rpkm,",
    "  file.path(project_dir, \"data/processed/expression_log2rpkm.rds\")",
    ")",
    "",
    "message(",
    "  \"Expression matrices prepared: \",",
    "  nrow(expression_log2rpkm),",
    "  \" genes x \",",
    "  ncol(expression_log2rpkm),",
    "  \" samples.\"",
    ")"
  ),
  file.path(project_dir, "scripts/02_prepare_data.R"),
  useBytes = TRUE
)

writeLines(
  c(
    "# Run CEMiTool",
    "",
    "project_dir <- normalizePath(getwd(), winslash = \"/\", mustWork = TRUE)",
    "",
    "expression_log2rpkm <- readRDS(",
    "  file.path(project_dir, \"data/processed/expression_log2rpkm.rds\")",
    ")",
    "",
    "annot <- read.delim(",
    "  file.path(project_dir, \"data/metadata/phenotypes.tsv\"),",
    "  sep = \"\\t\",",
    "  header = TRUE,",
    "  stringsAsFactors = FALSE,",
    "  check.names = FALSE",
    ")",
    "",
    "stopifnot(",
    "  identical(colnames(expression_log2rpkm), annot$SampleName)",
    ")",
    "",
    "# Automatic beta selection failed for this baseline.",
    "# Beta 10 is fixed explicitly for the 54-sample analysis.",
    "# Re-evaluate this value if the sample set, normalization, or filtering changes.",
    "BETA_MANUAL <- 10",
    "BETA_STRATEGY <- \"manual_set_beta_beta10\"",
    "",
    "set.seed(1234)",
    "",
    "cem <- CEMiTool::cemitool(",
    "  expr = as.data.frame(",
    "    expression_log2rpkm,",
    "    check.names = FALSE",
    "  ),",
    "  annot = annot,",
    "  filter = TRUE,",
    "  filter_pval = 0.1,",
    "  apply_vst = FALSE,",
    "  cor_method = \"pearson\",",
    "  network_type = \"unsigned\",",
    "  tom_type = \"signed\",",
    "  set_beta = BETA_MANUAL,",
    "  force_beta = FALSE,",
    "  merge_similar = TRUE,",
    "  min_ngen = 30,",
    "  plot = TRUE,",
    "  plot_diagnostics = TRUE,",
    "  order_by_class = TRUE,",
    "  verbose = TRUE",
    ")",
    "",
    "if (CEMiTool::nmodules(cem) < 1) {",
    "  saveRDS(",
    "    cem,",
    "    file.path(project_dir, \"results/objects/cemitool_failed.rds\")",
    "  )",
    "  stop(\"CEMiTool returned no modules.\")",
    "}",
    "",
    "saveRDS(",
    "  cem,",
    "  file.path(project_dir, \"results/objects/cemitool.rds\")",
    ")",
    "",
    "message(",
    "  \"CEMiTool complete: \",",
    "  CEMiTool::nmodules(cem),",
    "  \" modules; beta=\",",
    "  BETA_MANUAL",
    ")"
  ),
  file.path(project_dir, "scripts/03_run_cemitool.R"),
  useBytes = TRUE
)

writeLines(
  c(
    "# Export CEMiTool results and reproducibility records",
    "",
    "project_dir <- normalizePath(getwd(), winslash = \"/\", mustWork = TRUE)",
    "",
    "cem <- readRDS(",
    "  file.path(project_dir, \"results/objects/cemitool.rds\")",
    ")",
    "",
    "dir.create(",
    "  file.path(project_dir, \"results/tables\"),",
    "  recursive = TRUE,",
    "  showWarnings = FALSE",
    ")",
    "",
    "dir.create(",
    "  file.path(project_dir, \"results/figures\"),",
    "  recursive = TRUE,",
    "  showWarnings = FALSE",
    ")",
    "",
    "report_figure_dir <- file.path(",
    "  project_dir,",
    "  \"reports/assets/figures\"",
    ")",
    "",
    "dir.create(",
    "  report_figure_dir,",
    "  recursive = TRUE,",
    "  showWarnings = FALSE",
    ")",
    "",
    "CEMiTool::write_files(",
    "  cem,",
    "  directory = file.path(project_dir, \"results/tables\"),",
    "  force = TRUE",
    ")",
    "",
    "# Keep the original CEMiTool vector PDFs as scientific output.",
    "CEMiTool::save_plots(",
    "  cem,",
    "  \"all\",",
    "  directory = file.path(project_dir, \"results/figures\"),",
    "  force = TRUE",
    ")",
    "",
    "# Word works more reliably with raster graphics. Instead of converting",
    "# CEMiTool PDFs with Poppler, save PNG copies directly from the plot objects.",
    "safe_name <- function(x) {",
    "  x <- gsub(\"[^A-Za-z0-9_-]+\", \"_\", x)",
    "  x <- gsub(\"_+\", \"_\", x)",
    "  gsub(\"^_|_$\", \"\", x)",
    "}",
    "",
    "save_plot_png <- function(plot_object, filename, width = 9, height = 6.5) {",
    "  if (is.null(plot_object)) {",
    "    return(FALSE)",
    "  }",
    "",
    "  tryCatch(",
    "    {",
    "      ggplot2::ggsave(",
    "        filename = filename,",
    "        plot = plot_object,",
    "        width = width,",
    "        height = height,",
    "        units = \"in\",",
    "        dpi = 300,",
    "        bg = \"white\",",
    "        limitsize = FALSE",
    "      )",
    "      TRUE",
    "    },",
    "    error = function(e) {",
    "      warning(",
    "        \"Could not save PNG figure \",",
    "        basename(filename),",
    "        \": \",",
    "        conditionMessage(e)",
    "      )",
    "      FALSE",
    "    }",
    "  )",
    "}",
    "",
    "plot_types <- c(",
    "  \"profile\",",
    "  \"gsea\",",
    "  \"ora\",",
    "  \"interaction\",",
    "  \"beta_r2\",",
    "  \"mean_k\",",
    "  \"sample_tree\",",
    "  \"mean_var\",",
    "  \"hist\",",
    "  \"qq\"",
    ")",
    "",
    "for (plot_type in plot_types) {",
    "  plot_set <- tryCatch(",
    "    CEMiTool::show_plot(cem, plot_type),",
    "    error = function(e) NULL",
    "  )",
    "",
    "  if (is.null(plot_set)) {",
    "    next",
    "  }",
    "",
    "  is_single_plot <- inherits(",
    "    plot_set,",
    "    c(\"ggplot\", \"grob\", \"gtable\", \"gg\", \"patchwork\")",
    "  )",
    "",
    "  if (is_single_plot) {",
    "    plot_set <- list(plot_set)",
    "  } else if (!is.list(plot_set)) {",
    "    plot_set <- list(plot_set)",
    "  }",
    "",
    "  plot_names <- names(plot_set)",
    "",
    "  for (i in seq_along(plot_set)) {",
    "    label <- if (",
    "      !is.null(plot_names) &&",
    "      length(plot_names) >= i &&",
    "      !is.na(plot_names[[i]]) &&",
    "      nzchar(plot_names[[i]])",
    "    ) {",
    "      safe_name(plot_names[[i]])",
    "    } else {",
    "      sprintf(\"%02d\", i)",
    "    }",
    "",
    "    filename <- if (length(plot_set) == 1) {",
    "      paste0(plot_type, \".png\")",
    "    } else {",
    "      paste0(plot_type, \"_\", label, \".png\")",
    "    }",
    "",
    "    dimensions <- switch(",
    "      plot_type,",
    "      profile = c(10, 7),",
    "      sample_tree = c(11, 7),",
    "      gsea = c(9, 7),",
    "      interaction = c(9, 8),",
    "      c(9, 6.5)",
    "    )",
    "",
    "    save_plot_png(",
    "      plot_set[[i]],",
    "      file.path(report_figure_dir, filename),",
    "      width = dimensions[[1]],",
    "      height = dimensions[[2]]",
    "    )",
    "  }",
    "}",
    "",
    "beta <- tryCatch(",
    "  cem@parameters$beta,",
    "  error = function(e) NA",
    ")",
    "",
    "r2 <- tryCatch(",
    "  cem@parameters$r2,",
    "  error = function(e) NA",
    ")",
    "",
    "beta_fit <- tryCatch(",
    "  CEMiTool::fit_data(cem),",
    "  error = function(e) NULL",
    ")",
    "",
    "if (!is.null(beta_fit)) {",
    "  write.table(",
    "    beta_fit,",
    "    file.path(project_dir, \"results/tables/beta_fit_indices.tsv\"),",
    "    sep = \"\\t\",",
    "    quote = FALSE,",
    "    row.names = FALSE",
    "  )",
    "}",
    "",
    "if (is.finite(r2) && r2 < 0.60) {",
    "  warning(",
    "    \"The recorded scale-free fit for beta 10 is below 0.60. \",",
    "    \"Inspect the diagnostic report before interpreting modules.\"",
    "  )",
    "}",
    "",
    "writeLines(",
    "  capture.output(sessionInfo()),",
    "  file.path(project_dir, \"logs/session_info.txt\")",
    ")",
    "",
    "writeLines(",
    "  c(",
    "    \"dataset=GSE98923\",",
    "    \"samples=54\",",
    "    \"transform=log2(RPKM+1)\",",
    "    \"correlation=pearson\",",
    "    \"network_type=unsigned\",",
    "    \"tom_type=signed\",",
    "    \"beta_strategy=manual_set_beta_beta10\",",
    "    \"set_beta=10\",",
    "    \"force_beta=FALSE\",",
    "    paste0(\"beta=\", beta),",
    "    paste0(\"r2=\", r2),",
    "    \"filter=TRUE\",",
    "    \"filter_pval=0.1\",",
    "    \"min_module_size=30\",",
    "    \"seed=1234\",",
    "    paste0(\"modules=\", CEMiTool::nmodules(cem))",
    "  ),",
    "  file.path(project_dir, \"logs/parameters.txt\")",
    ")",
    "",
    "writeLines(",
    "  c(",
    "    \"GSE98923 CEMiTool baseline\",",
    "    paste0(\"completed=\", Sys.time()),",
    "    paste0(\"modules=\", CEMiTool::nmodules(cem)),",
    "    \"beta_strategy=manual_set_beta_beta10\",",
    "    paste0(\"beta=\", beta),",
    "    paste0(\"r2=\", r2)",
    "  ),",
    "  file.path(project_dir, \"logs/run_summary.txt\")",
    ")",
    "",
    "message(\"CEMiTool tables, vector figures, PNG report figures, and logs exported.\")"
  ),
  file.path(project_dir, "scripts/04_export_results.R"),
  useBytes = TRUE
)

writeLines(
  c(
    "# Render native CEMiTool reports, technical reports, and manuscript draft",
    "",
    "project_dir <- normalizePath(getwd(), winslash = \"/\", mustWork = TRUE)",
    "",
    "required <- c(",
    "  \"rmarkdown\",",
    "  \"knitr\",",
    "  \"tinytex\",",
    "  \"zip\"",
    ")",
    "",
    "missing <- required[",
    "  !vapply(required, requireNamespace, logical(1), quietly = TRUE)",
    "]",
    "",
    "if (length(missing) > 0) {",
    "  install.packages(missing)",
    "}",
    "",
    "report_dir <- file.path(project_dir, \"reports\")",
    "cemitool_report_dir <- file.path(report_dir, \"cemitool\")",
    "diagnostic_report_dir <- file.path(report_dir, \"diagnostics\")",
    "assets_dir <- file.path(report_dir, \"assets/figures\")",
    "supp_dir <- file.path(report_dir, \"supplementary\")",
    "manuscript_dir <- file.path(project_dir, \"manuscript\")",
    "",
    "dirs <- c(",
    "  report_dir,",
    "  cemitool_report_dir,",
    "  diagnostic_report_dir,",
    "  assets_dir,",
    "  supp_dir,",
    "  manuscript_dir",
    ")",
    "",
    "invisible(lapply(",
    "  dirs,",
    "  dir.create,",
    "  recursive = TRUE,",
    "  showWarnings = FALSE",
    "))",
    "",
    "cem <- readRDS(",
    "  file.path(project_dir, \"results/objects/cemitool.rds\")",
    ")",
    "",
    "# Native CEMiTool reports",
    "native_report_status <- data.frame(",
    "  report = c(\"cemitool\", \"diagnostics\"),",
    "  success = c(FALSE, FALSE),",
    "  message = c(\"\", \"\"),",
    "  stringsAsFactors = FALSE",
    ")",
    "",
    "native_report_status$success[1] <- tryCatch(",
    "  {",
    "    CEMiTool::generate_report(",
    "      cem,",
    "      title = \"GSE98923 CEMiTool analysis - beta 10\",",
    "      directory = cemitool_report_dir,",
    "      force = TRUE,",
    "      output_format = \"html_document\"",
    "    )",
    "    native_report_status$message[1] <- \"Generated successfully\"",
    "    TRUE",
    "  },",
    "  error = function(e) {",
    "    native_report_status$message[1] <- conditionMessage(e)",
    "    warning(",
    "      \"Could not generate the native CEMiTool report: \",",
    "      conditionMessage(e)",
    "    )",
    "    FALSE",
    "  }",
    ")",
    "",
    "native_report_status$success[2] <- tryCatch(",
    "  {",
    "    CEMiTool::diagnostic_report(",
    "      cem,",
    "      title = \"GSE98923 CEMiTool diagnostics - beta 10\",",
    "      directory = diagnostic_report_dir,",
    "      force = TRUE,",
    "      output_format = \"html_document\"",
    "    )",
    "    native_report_status$message[2] <- \"Generated successfully\"",
    "    TRUE",
    "  },",
    "  error = function(e) {",
    "    native_report_status$message[2] <- conditionMessage(e)",
    "    warning(",
    "      \"Could not generate the native CEMiTool diagnostic report: \",",
    "      conditionMessage(e)",
    "    )",
    "    FALSE",
    "  }",
    ")",
    "",
    "write.table(",
    "  native_report_status,",
    "  file.path(report_dir, \"native_report_status.tsv\"),",
    "  sep = \"\\t\",",
    "  quote = FALSE,",
    "  row.names = FALSE",
    ")",
    "",
    "# PNG figures are created directly from R plot objects in 04_export_results.R.",
    "png_figures <- list.files(",
    "  assets_dir,",
    "  pattern = \"\\\\.(png|jpg|jpeg)$\",",
    "  full.names = TRUE,",
    "  recursive = TRUE,",
    "  ignore.case = TRUE",
    ")",
    "",
    "if (length(png_figures) == 0) {",
    "  warning(",
    "    \"No report-compatible PNG figures were found in reports/assets/figures/. \",",
    "    \"The reports will still render, but their figure section may be empty.\"",
    "  )",
    "}",
    "",
    "# Supplementary manifest",
    "supp_files <- unique(c(",
    "  list.files(",
    "    file.path(project_dir, \"data/metadata\"),",
    "    full.names = TRUE,",
    "    recursive = TRUE",
    "  ),",
    "  list.files(",
    "    file.path(project_dir, \"data/processed\"),",
    "    full.names = TRUE,",
    "    recursive = TRUE",
    "  ),",
    "  list.files(",
    "    file.path(project_dir, \"results/tables\"),",
    "    full.names = TRUE,",
    "    recursive = TRUE",
    "  ),",
    "  list.files(",
    "    file.path(project_dir, \"results/figures\"),",
    "    full.names = TRUE,",
    "    recursive = TRUE",
    "  ),",
    "  list.files(",
    "    cemitool_report_dir,",
    "    full.names = TRUE,",
    "    recursive = TRUE",
    "  ),",
    "  list.files(",
    "    diagnostic_report_dir,",
    "    full.names = TRUE,",
    "    recursive = TRUE",
    "  ),",
    "  file.path(project_dir, \"logs/parameters.txt\"),",
    "  file.path(project_dir, \"logs/session_info.txt\"),",
    "  file.path(project_dir, \"logs/run_summary.txt\"),",
    "  file.path(report_dir, \"native_report_status.tsv\")",
    "))",
    "",
    "supp_files <- supp_files[",
    "  file.exists(supp_files) &",
    "  !dir.exists(supp_files)",
    "]",
    "",
    "relative_path <- function(path) {",
    "  normalized <- normalizePath(",
    "    path,",
    "    winslash = \"/\",",
    "    mustWork = TRUE",
    "  )",
    "",
    "  prefix <- paste0(",
    "    normalizePath(",
    "      project_dir,",
    "      winslash = \"/\",",    "      mustWork = TRUE",
    "    ),",
    "    \"/\"",
    "  )",
    "",
    "  substring(",
    "    normalized,",
    "    nchar(prefix) + 1",
    "  )",
    "}",
    "",
    "manifest <- data.frame(",
    "  file = vapply(",
    "    supp_files,",
    "    relative_path,",
    "    character(1)",
    "  ),",
    "  bytes = as.numeric(file.info(supp_files)$size),",
    "  md5 = unname(tools::md5sum(supp_files)),",
    "  stringsAsFactors = FALSE",
    ")",
    "",
    "manifest <- manifest[order(manifest$file), ]",
    "",
    "write.table(",
    "  manifest,",
    "  file.path(supp_dir, \"manifest.tsv\"),",
    "  sep = \"\\t\",",
    "  quote = FALSE,",
    "  row.names = FALSE",
    ")",
    "",
    "supp_zip <- file.path(",
    "  supp_dir,",
    "  \"gse98923_supplementary_files.zip\"",
    ")",
    "",
    "if (file.exists(supp_zip)) {",
    "  file.remove(supp_zip)",
    "}",
    "",
    "old_wd <- getwd()",
    "setwd(project_dir)",
    "on.exit(setwd(old_wd), add = TRUE)",
    "",
    "zip::zipr(",
    "  zipfile = supp_zip,",
    "  files = manifest$file",
    ")",
    "",
    "# Consolidated technical report",
    "ensure_latex <- function() {",
    "  has_xelatex <- nzchar(Sys.which(\"xelatex\"))",
    "",
    "  if (!has_xelatex && !tinytex::is_tinytex()) {",
    "    message(",
    "      \"No LaTeX installation was found. Installing TinyTeX once for PDF output.\"",
    "    )",
    "",
    "    try(",
    "      tinytex::install_tinytex(),",
    "      silent = TRUE",
    "    )",
    "  }",
    "",
    "  nzchar(Sys.which(\"xelatex\")) || tinytex::is_tinytex()",
    "}",
    "",
    "render_one <- function(input, format, output_file, output_dir) {",
    "  tryCatch(",
    "    {",
    "      rmarkdown::render(",
    "        input = input,",
    "        output_format = format,",
    "        output_file = output_file,",
    "        output_dir = output_dir,",
    "        envir = new.env(parent = globalenv()),",
    "        quiet = TRUE",
    "      )",
    "",
    "      message(",
    "        \"Created: \",",
    "        file.path(output_dir, output_file)",
    "      )",
    "",
    "      TRUE",
    "    },",
    "    error = function(e) {",
    "      warning(",
    "        \"Could not render \",",
    "        output_file,",
    "        \": \",",
    "        conditionMessage(e)",
    "      )",
    "",
    "      FALSE",
    "    }",
    "  )",
    "}",
    "",
    "analysis_template <- file.path(",
    "  project_dir,",
    "  \"templates/analysis_report.Rmd\"",
    ")",
    "",
    "analysis_status <- data.frame(",
    "  format = c(\"html\", \"docx\", \"pdf\"),",
    "  success = c(FALSE, FALSE, FALSE),",
    "  stringsAsFactors = FALSE",
    ")",
    "",
    "analysis_status$success[1] <- render_one(",
    "  analysis_template,",
    "  \"html_document\",",
    "  \"analysis_report.html\",",
    "  report_dir",
    ")",
    "",
    "analysis_status$success[2] <- render_one(",
    "  analysis_template,",
    "  \"word_document\",",
    "  \"analysis_report.docx\",",
    "  report_dir",
    ")",
    "",
    "if (ensure_latex()) {",
    "  analysis_status$success[3] <- render_one(",
    "    analysis_template,",
    "    \"pdf_document\",",
    "    \"analysis_report.pdf\",",
    "    report_dir",
    "  )",
    "} else {",
    "  warning(",
    "    \"PDF report was skipped because no working LaTeX installation is available.\"",
    "  )",
    "}",
    "",
    "write.table(",
    "  analysis_status,",
    "  file.path(report_dir, \"analysis_report_status.tsv\"),",
    "  sep = \"\\t\",",
    "  quote = FALSE,",
    "  row.names = FALSE",
    ")",
    "",
    "# Scientific manuscript scaffold",
    "article_source <- file.path(",
    "  project_dir,",
    "  \"templates/article_draft.Rmd\"",
    ")",
    "",
    "article_copy <- file.path(",
    "  manuscript_dir,",
    "  \"article_draft.Rmd\"",
    ")",
    "",
    "file.copy(",
    "  article_source,",
    "  article_copy,",
    "  overwrite = TRUE",
    ")",
    "",
    "article_status <- data.frame(",
    "  format = c(\"docx\", \"pdf\"),",
    "  success = c(FALSE, FALSE),",
    "  stringsAsFactors = FALSE",
    ")",
    "",
    "article_status$success[1] <- render_one(",
    "  article_copy,",
    "  \"word_document\",",
    "  \"article_draft.docx\",",
    "  manuscript_dir",
    ")",
    "",
    "if (ensure_latex()) {",
    "  article_status$success[2] <- render_one(",
    "    article_copy,",
    "    \"pdf_document\",",
    "    \"article_draft.pdf\",",
    "    manuscript_dir",
    "  )",
    "}",
    "",
    "write.table(",
    "  article_status,",
    "  file.path(manuscript_dir, \"article_render_status.tsv\"),",
    "  sep = \"\\t\",",
    "  quote = FALSE,",
    "  row.names = FALSE",
    ")",
    "",
    "# Human-readable report index",
    "writeLines(",
    "  c(",
    "    \"# Report index\",",
    "    \"\",",
    "    \"## Native CEMiTool reports\",",
    "    \"\",",
    "    \"- reports/cemitool/: native CEMiTool analysis report\",",
    "    \"- reports/diagnostics/: native CEMiTool diagnostic report\",",
    "    \"\",",
    "    \"## Consolidated technical report\",",
    "    \"\",",
    "    \"- reports/analysis_report.html\",",
    "    \"- reports/analysis_report.docx\",",
    "    \"- reports/analysis_report.pdf\",",
    "    \"\",",
    "    \"## Scientific manuscript scaffold\",",
    "    \"\",",
    "    \"- manuscript/article_draft.Rmd\",",
    "    \"- manuscript/article_draft.docx\",",
    "    \"- manuscript/article_draft.pdf\",",
    "    \"\",",
    "    \"## Supplementary material\",",
    "    \"\",",
    "    \"- reports/supplementary/manifest.tsv\",",
    "    \"- reports/supplementary/gse98923_supplementary_files.zip\",",
    "    \"\",",
    "    \"The native CEMiTool reports, consolidated report, and manuscript draft\",",
    "    \"serve different purposes and are intentionally kept together.\"",
    "  ),",
    "  file.path(report_dir, \"README.md\")",
    ")",
    "",
    "message(",
    "  \"Report generation complete: native CEMiTool reports, consolidated \",",
    "  \"HTML/Word/PDF report, manuscript draft, and supplementary package.\"",
    ")"
  ),
  file.path(project_dir, "scripts/05_render_reports.R"),
  useBytes = TRUE
)

writeLines(
  c(
    "---",
    "title: \"GSE98923 co-expression analysis\"",
    "subtitle: \"CEMiTool baseline - 54-sample balanced design\"",
    "date: \"`r format(Sys.Date(), '%Y-%m-%d')`\"",
    "output:",
    "  html_document:",
    "    toc: true",
    "    toc_float: true",
    "    number_sections: true",
    "    df_print: paged",
    "  word_document:",
    "    toc: true",
    "    number_sections: true",
    "  pdf_document:",
    "    toc: true",
    "    number_sections: true",
    "    latex_engine: xelatex",
    "fontsize: 11pt",
    "geometry: margin=1in",
    "---",
    "",
    "```{r setup, include=FALSE}",
    "knitr::opts_chunk$set(",
    "  echo = FALSE,",
    "  warning = FALSE,",
    "  message = FALSE,",
    "  fig.align = \"center\",",
    "  out.width = \"92%\"",
    ")",
    "",
    "project_dir <- normalizePath(\"..\", winslash = \"/\", mustWork = TRUE)",
    "",
    "samples <- read.delim(",
    "  file.path(project_dir, \"data/metadata/samples.tsv\"),",
    "  sep = \"\\t\",",
    "  stringsAsFactors = FALSE,",
    "  check.names = FALSE",
    ")",
    "",
    "expr <- readRDS(",
    "  file.path(project_dir, \"data/processed/expression_log2rpkm.rds\")",
    ")",
    "",
    "cem <- readRDS(",
    "  file.path(project_dir, \"results/objects/cemitool.rds\")",
    ")",
    "",
    "param_file <- file.path(project_dir, \"logs/parameters.txt\")",
    "parameters <- if (file.exists(param_file)) {",
    "  readLines(param_file)",
    "} else {",
    "  character()",
    "}",
    "",
    "param_value <- function(key) {",
    "  hit <- grep(paste0(\"^\", key, \"=\"), parameters, value = TRUE)",
    "  if (length(hit) == 0) return(NA_character_)",
    "  sub(paste0(\"^\", key, \"=\"), \"\", hit[[1]])",
    "}",
    "",
    "n_modules <- CEMiTool::nmodules(cem)",
    "beta <- param_value(\"beta\")",
    "```",
    "",
    "# Scope",
    "",
    "This report documents the computational analysis of the balanced 54-sample subset of GEO accession **GSE98923** used in the CEMiTool baseline workflow.",
    "",
    "The report is intended as an analysis record and potential supplementary document for a scientific manuscript. Large machine-readable matrices are not printed in full in the document; complete files are preserved separately and indexed in the supplementary manifest.",
    "",
    "# Experimental design",
    "",
    "The analysis contains **`r nrow(samples)` samples**, covering two cultivars, three developmental stages, three years, and three biological replicates per cultivar-stage-year combination.",
    "",
    "```{r design-table}",
    "design <- with(samples, table(Cultivar, Stage, Year))",
    "knitr::kable(",
    "  as.data.frame(design),",
    "  caption = \"Sample counts by cultivar, developmental stage, and year.\"",
    ")",
    "```",
    "",
    "# Expression data",
    "",
    "The processed matrix used for CEMiTool contains **`r nrow(expr)` genes** and **`r ncol(expr)` samples**.",
    "",
    "Expression values were derived from the processed RPKM matrix distributed with GSE98923 and transformed as:",
    "",
    "\\[",
    "\\log_2(\\mathrm{RPKM} + 1)",
    "\\]",
    "",
    "The complete matrices are available under:",
    "",
    "- `data/processed/expression_rpkm.tsv`",
    "- `data/processed/expression_log2rpkm.tsv`",
    "",
    "# CEMiTool analysis",
    "",
    "CEMiTool identified **`r n_modules` modules** in the baseline analysis.",
    "",
    "The analysis used Pearson correlation, an unsigned network, a signed TOM, a minimum module size of 30, and a fixed random seed of 1234.",
    "",
    "Automatic beta selection did not identify a usable value in the initial baseline run. To reproduce the established 54-sample baseline, the soft-thresholding power was fixed explicitly at **beta = 10** using `set_beta = 10` and `force_beta = FALSE`. This value is specific to the present expression matrix and should be re-evaluated if the sample set, normalization, or filtering changes. The recorded beta for this run is **`r beta`**.",
    "",
    "```{r parameters-table}",
    "if (length(parameters) > 0) {",
    "  p <- do.call(",
    "    rbind,",
    "    strsplit(parameters, \"=\", fixed = TRUE)",
    "  )",
    "  p <- as.data.frame(p, stringsAsFactors = FALSE)",
    "  names(p) <- c(\"parameter\", \"value\")",
    "  knitr::kable(p, caption = \"Recorded analysis parameters.\")",
    "}",
    "```",
    "",
    "# Diagnostic and analysis figures",
    "",
    "All figures generated by the analysis are stored in `results/figures/`. PDF figures are converted to PNG copies for reliable inclusion in Word and HTML reports.",
    "",
    "```{r figures, results='asis'}",
    "figure_dir <- file.path(project_dir, \"reports/assets/figures\")",
    "",
    "figure_files <- list.files(",
    "  figure_dir,",
    "  pattern = \"\\\\.(png|jpg|jpeg)$\",",
    "  full.names = TRUE,",
    "  recursive = TRUE,",
    "  ignore.case = TRUE",
    ")",
    "",
    "if (length(figure_files) == 0) {",
    "  cat(\"No report-compatible figure files were found.\\n\")",
    "} else {",
    "  for (f in figure_files) {",
    "    cat(\"\\n## \", tools::file_path_sans_ext(basename(f)), \"\\n\\n\", sep = \"\")",
    "    print(knitr::include_graphics(f))",
    "    cat(\"\\n\")",
    "  }",
    "}",
    "```",
    "",
    "# Exported result tables",
    "",
    "The following section provides a compact view of every tabular result exported by CEMiTool. Complete tables remain available as machine-readable files under `results/tables/`.",
    "",
    "```{r result-tables, results='asis'}",
    "table_files <- list.files(",
    "  file.path(project_dir, \"results/tables\"),",
    "  pattern = \"\\\\.(tsv|csv|txt)$\",",
    "  full.names = TRUE,",
    "  recursive = TRUE,",
    "  ignore.case = TRUE",
    ")",
    "",
    "read_result_table <- function(path) {",
    "  ext <- tolower(tools::file_ext(path))",
    "",
    "  if (ext == \"csv\") {",
    "    read.csv(",
    "      path,",
    "      stringsAsFactors = FALSE,",
    "      check.names = FALSE",
    "    )",
    "  } else {",
    "    read.delim(",
    "      path,",
    "      sep = \"\\t\",",
    "      stringsAsFactors = FALSE,",
    "      check.names = FALSE",
    "    )",
    "  }",
    "}",
    "",
    "if (length(table_files) == 0) {",
    "  cat(\"No exported result tables were found.\\n\")",
    "} else {",
    "  for (f in table_files) {",
    "    cat(\"\\n## \", basename(f), \"\\n\\n\", sep = \"\")",
    "",
    "    x <- tryCatch(",
    "      read_result_table(f),",
    "      error = function(e) NULL",
    "    )",
    "",
    "    if (is.null(x)) {",
    "      cat(\"The table could not be displayed in the report. See the original file.\\n\")",
    "      next",
    "    }",
    "",
    "    cat(",
    "      \"Dimensions: \",",
    "      nrow(x),",
    "      \" rows x \",",
    "      ncol(x),",
    "      \" columns.\\n\\n\",",
    "      sep = \"\"",
    "    )",
    "",
    "    display_n <- min(nrow(x), 40)",
    "",
    "    print(",
    "      knitr::kable(",
    "        utils::head(x, display_n),",
    "        caption = paste0(",
    "          basename(f),",
    "          if (nrow(x) > display_n) {",
    "            paste0(\" - first \", display_n, \" rows shown\")",
    "          } else {",
    "            \"\"",
    "          }",
    "        )",
    "      )",
    "    )",
    "",
    "    if (nrow(x) > display_n) {",
    "      cat(",
    "        \"\\nThe complete table is provided as a supplementary machine-readable file.\\n\"",
    "      )",
    "    }",
    "  }",
    "}",
    "```",
    "",
    "# Supplementary data inventory",
    "",
    "The full analysis files are indexed in `reports/supplementary/manifest.tsv`. The manifest records relative paths, file sizes, and MD5 checksums.",
    "",
    "```{r supplement-manifest}",
    "manifest_file <- file.path(",
    "  project_dir,",
    "  \"reports/supplementary/manifest.tsv\"",
    ")",
    "",
    "if (file.exists(manifest_file)) {",
    "  manifest <- read.delim(",
    "    manifest_file,",
    "    sep = \"\\t\",",
    "    stringsAsFactors = FALSE,",
    "    check.names = FALSE",
    "  )",
    "",
    "  knitr::kable(",
    "    manifest,",
    "    caption = \"Supplementary file inventory.\"",
    "  )",
    "}",
    "```",
    "",
    "# Reproducibility",
    "",
    "```{r session-info}",
    "session_file <- file.path(project_dir, \"logs/session_info.txt\")",
    "",
    "if (file.exists(session_file)) {",
    "  cat(\"```text\\n\")",
    "  cat(readLines(session_file), sep = \"\\n\")",
    "  cat(\"\\n```\\n\")",
    "}",
    "```",
    "",
    "# Notes for manuscript use",
    "",
    "This document is a computational analysis report, not a substitute for biological interpretation. Statements about biological mechanism, causal relationships, novelty, and comparison with previous literature should be supported separately with appropriate experimental evidence and verified references."
  ),
  file.path(project_dir, "templates/analysis_report.Rmd"),
  useBytes = TRUE
)

writeLines(
  c(
    "---",
    "title: \"[Manuscript title]\"",
    "author:",
    "  - \"[Author 1]\"",
    "  - \"[Author 2]\"",
    "date: \"`r format(Sys.Date(), '%Y-%m-%d')`\"",
    "bibliography: references.bib",
    "output:",
    "  word_document:",
    "    toc: false",
    "  pdf_document:",
    "    latex_engine: xelatex",
    "fontsize: 11pt",
    "geometry: margin=1in",
    "---",
    "",
    "```{r setup, include=FALSE}",
    "knitr::opts_chunk$set(",
    "  echo = FALSE,",
    "  warning = FALSE,",
    "  message = FALSE,",
    "  fig.align = \"center\",",
    "  out.width = \"88%\"",
    ")",
    "",
    "project_dir <- normalizePath(\"..\", winslash = \"/\", mustWork = TRUE)",
    "",
    "samples <- read.delim(",
    "  file.path(project_dir, \"data/metadata/samples.tsv\"),",
    "  sep = \"\\t\",",
    "  stringsAsFactors = FALSE,",
    "  check.names = FALSE",
    ")",
    "",
    "expr <- readRDS(",
    "  file.path(project_dir, \"data/processed/expression_log2rpkm.rds\")",
    ")",
    "",
    "cem <- readRDS(",
    "  file.path(project_dir, \"results/objects/cemitool.rds\")",
    ")",
    "",
    "parameters <- readLines(",
    "  file.path(project_dir, \"logs/parameters.txt\")",
    ")",
    "",
    "param_value <- function(key) {",
    "  hit <- grep(paste0(\"^\", key, \"=\"), parameters, value = TRUE)",
    "  if (length(hit) == 0) return(NA_character_)",
    "  sub(paste0(\"^\", key, \"=\"), \"\", hit[[1]])",
    "}",
    "```",
    "",
    "# Abstract",
    "",
    "[Write the final abstract after the biological results have been interpreted and verified.]",
    "",
    "# Introduction",
    "",
    "[Add the literature-supported biological background, study rationale, and research question. Insert only verified references in `references.bib`.]",
    "",
    "# Materials and Methods",
    "",
    "## Dataset and experimental design",
    "",
    "Publicly available expression data were obtained from GEO accession GSE98923. The baseline analysis used a balanced subset of **`r nrow(samples)` samples** comprising Cabernet Sauvignon and Pinot noir, three developmental stages (FruitSet, Veraison, and Harvest), three years (2012-2014), and three replicates per cultivar-stage-year combination.",
    "",
    "## Expression preprocessing",
    "",
    "The processed RPKM matrix distributed with GSE98923 was used as the expression source. The selected expression matrix contained **`r nrow(expr)` genes** across **`r ncol(expr)` samples**. Values were transformed as \\(\\log_2(\\mathrm{RPKM}+1)\\) before co-expression analysis.",
    "",
    "## Co-expression network analysis",
    "",
    "Gene co-expression analysis was performed in R using CEMiTool. Pearson correlation was used with an unsigned network and signed TOM. CEMiTool filtering was enabled with `filter_pval = 0.1`, `apply_vst = FALSE`, and a minimum module size of 30.",
    "",
    "Automatic beta selection did not return a usable value in the initial baseline analysis. For reproducibility of the established baseline, the soft-thresholding power was fixed at **beta = 10** with `set_beta = 10` and `force_beta = FALSE`. This parameter is specific to the present sample set and preprocessing and should be re-evaluated if either changes. A random seed of 1234 was used.",
    "",
    "Software versions are provided in `logs/session_info.txt`.",
    "",
    "# Results",
    "",
    "## Co-expression modules",
    "",
    "CEMiTool identified **`r CEMiTool::nmodules(cem)` modules** in the baseline analysis.",
    "",
    "[Describe the biologically relevant module patterns after inspecting the module profiles, enrichment results, and hub genes. Avoid interpreting module function solely from visual appearance.]",
    "",
    "## Figures",
    "",
    "[Select only manuscript-relevant figures from `results/figures/`. The full technical report contains the complete analysis figure set.]",
    "",
    "## Tables",
    "",
    "[Move the principal manuscript tables here. Complete machine-readable tables are stored under `results/tables/` and indexed in the supplementary manifest.]",
    "",
    "# Discussion",
    "",
    "[Interpret the findings in relation to grape berry development and the relevant literature. Discuss limitations, including the use of processed RPKM values, the fixed beta = 10 baseline choice, the selected 54-sample baseline design, and any potential year/cultivar effects.]",
    "",
    "# Conclusions",
    "",
    "[Write concise conclusions supported directly by the results.]",
    "",
    "# Data and code availability",
    "",
    "The analysis uses public data from GEO accession GSE98923. The reproducible project contains the sample selection, processing scripts, exported results, software-session information, and a supplementary file manifest with MD5 checksums.",
    "",
    "# References"
  ),
  file.path(project_dir, "templates/article_draft.Rmd"),
  useBytes = TRUE
)

writeLines(
  c(
    "# GSE98923 CEMiTool analysis",
    "",
    "Reproducible co-expression analysis of a balanced 54-sample subset from GEO accession **GSE98923**.",
    "",
    "The project is organized for a scientific manuscript workflow: raw data, metadata, processed data, analysis outputs, figures, reports, manuscript files, and reproducibility records are kept separate.",
    "",
    "## Project structure",
    "",
    "```text",
    "gse98923_cemitool/",
    "├── gse98923_cemitool.Rproj",
    "├── README.md",
    "├── run_all.R",
    "├── scripts/",
    "│   ├── 00_setup.R",
    "│   ├── 01_download_geo.R",
    "│   ├── 02_prepare_data.R",
    "│   ├── 03_run_cemitool.R",
    "│   ├── 04_export_results.R",
    "│   └── 05_render_reports.R",
    "├── templates/",
    "│   ├── analysis_report.Rmd",
    "│   └── article_draft.Rmd",
    "├── data/",
    "│   ├── raw/",
    "│   │   ├── geo/",
    "│   │   └── images/",
    "│   ├── metadata/",
    "│   └── processed/",
    "├── results/",
    "│   ├── objects/",
    "│   ├── tables/",
    "│   └── figures/",
    "├── reports/",
    "│   ├── cemitool/",
    "│   ├── diagnostics/",
    "│   ├── analysis_report.html",
    "│   ├── analysis_report.docx",
    "│   ├── analysis_report.pdf",
    "│   ├── assets/",
    "│   └── supplementary/",
    "├── manuscript/",
    "│   ├── article_draft.docx",
    "│   ├── article_draft.pdf",
    "│   └── references.bib",
    "├── docs/",
    "│   └── reference_images/",
    "└── logs/",
    "    ├── session_info.txt",
    "    ├── parameters.txt",
    "    └── run_summary.txt",
    "```",
    "",
    "## Reproducible workflow",
    "",
    "For normal scientific work, run the modular scripts in order:",
    "",
    "```r",
    "source(\"scripts/00_setup.R\")",
    "source(\"scripts/01_download_geo.R\")",
    "source(\"scripts/02_prepare_data.R\")",
    "source(\"scripts/03_run_cemitool.R\")",
    "source(\"scripts/04_export_results.R\")",
    "source(\"scripts/05_render_reports.R\")",
    "```",
    "",
    "For a clean machine or an empty directory, the complete workflow can be launched with:",
    "",
    "```r",
    "source(\"run_all.R\")",
    "```",
    "",
    "`run_all.R` contains the exact 54-sample selection used for this baseline. It creates the project structure, installs missing R packages, downloads the public GEO data, prepares the expression matrices, runs CEMiTool, exports results, and renders the reports.",
    "",
    "## Reports",
    "",
    "The workflow produces three versions of the technical report:",
    "",
    "- `reports/analysis_report.html`",
    "- `reports/analysis_report.docx` - editable in Microsoft Word / LibreOffice",
    "- `reports/analysis_report.pdf`",
    "",
    "The PDF build uses LaTeX. If no LaTeX installation is found, the workflow attempts to install TinyTeX once.",
    "",
    "The report embeds all analysis figures and compact views of exported result tables. Very large expression matrices and large result tables are intentionally not printed in full inside Word/PDF because that is poor scientific reporting practice. Their complete versions remain as machine-readable supplementary files and are indexed with checksums under `reports/supplementary/`.",
    "",
    "## Manuscript draft",
    "",
    "The workflow also renders:",
    "",
    "- `manuscript/article_draft.docx`",
    "- `manuscript/article_draft.pdf`",
    "",
    "This is an editable scientific-article scaffold. Computational methods and basic dataset/result summaries are filled automatically. Literature-dependent sections such as Introduction and Discussion remain clearly marked for author writing rather than being fabricated by the pipeline.",
    "",
    "## Images",
    "",
    "Original experimental sample photographs, if they genuinely exist, belong in:",
    "",
    "```text",
    "data/raw/images/",
    "```",
    "",
    "and should be indexed in:",
    "",
    "```text",
    "data/metadata/sample_images.tsv",
    "```",
    "",
    "Images copied from papers, websites, presentations, or other secondary sources belong in:",
    "",
    "```text",
    "docs/reference_images/",
    "```",
    "",
    "They should not be presented as original sample photographs.",
    "",
    "## Reproducibility",
    "",
    "Raw GEO files are not edited manually. Processed files are regenerated from scripts. Software versions, analysis parameters, and file checksums are recorded under `logs/` and `reports/supplementary/`.",
    "",
    "",
    "## Native CEMiTool reports",
    "",
    "The workflow also creates the package-native HTML reports:",
    "",
    "- `reports/cemitool/` - CEMiTool analysis report",
    "- `reports/diagnostics/` - CEMiTool diagnostic report",
    "",
    "These are retained alongside the consolidated HTML/Word/PDF report because",
    "they provide package-specific diagnostic and module views that are useful",
    "for review and reproducibility."
  ),
  file.path(project_dir, "README.md"),
  useBytes = TRUE
)


source(file.path(project_dir, "scripts/00_setup.R"))
source(file.path(project_dir, "scripts/01_download_geo.R"))
source(file.path(project_dir, "scripts/02_prepare_data.R"))
source(file.path(project_dir, "scripts/03_run_cemitool.R"))
source(file.path(project_dir, "scripts/04_export_results.R"))
source(file.path(project_dir, "scripts/05_render_reports.R"))

message(
  "Complete workflow finished. Beta was fixed at 10. ",
  "See reports/README.md for the report inventory."
)